name = "iCSV"
uuid = "1fbc523b-fa59-4a4c-89bb-0e3fcf7c697f"
authors = ["patrick.leibersperger <patrick.leibersperger@slf.ch> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
